name: CI

on:
  pull_request:

  push:
    branches: [ main ]

jobs:
  test-style:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Installation
      run: |
        sudo apt update
        sudo apt install python3 python3-pip
        pip install black mypy

    - name: Style check
      run: black --check repl

    - name: Type check
      run: mypy repl